import { Router } from "express";

import workspaceRoutes from "./modules/workspace/workspace.routes.js";
import parserRoutes from "./modules/parser/parser.routes.js";
import chunkRoutes from "./modules/chunk/chunk.routes.js";
import graphRoutes from "./modules/graph/graph.routes.js";
import indexerRoutes from "./modules/indexer/indexer.routes.js";
import fileRoutes from "./modules/file/file.routes.js";
import resolverRoutes from "./modules/resolver/resolver.route.js";
import architectureRoutes from "./modules/architecture/architecture.routes.js";
import explainerRoutes from "./modules/explainer/explainer.routes.js";
import decisionRoutes from "./modules/decision/decision.routes.js";
import contextRoutes from "./modules/context/context.routes.js";
import intentRoutes from "./modules/intent/intent.routes.js";
import intelligenceRoutes from "./modules/intelligence/intelligence.routes.js";
import plannerRoutes from "./modules/planner/planner.routes.js";
import refactorRoutes from "./modules/refactor/refactor.routes.js";
import transformationRoutes from "./modules/transformation/transformation.routes.js";
import callgraphRoutes from "./modules/callgraph/callgraph.routes.js";
import refactorPlanRoutes from "./modules/refactor-plan/refactor-plan.routes.js";
import changesetRoutes from "./modules/changeset/changeset.routes.js";
import astRefactorRoutes from "./modules/ast-refactor/ast-refactor.routes.js";
import changeSetExecutorRoutes from "./modules/changeset-executor/changeset-executor.routes.js";
import diffPreviewRoutes from "./modules/diff-preview/diff-preview.routes.js";
import snapshotRoutes from "./modules/snapshot/snapshot.routes.js";
import embeddingRoutes from "./modules/embedding/embedding.routes.js";
import aiRoutes from "./modules/ai/ai.routes.js";
import repositoryRoutes from "./modules/repository/repository.routes.js";
import authRoutes from "./modules/auth/auth.routes.js";
import { verifyToken } from "./middlewares/auth.middleware.js";
import flowExplainRoutes from "./modules/flow-explainer/flow-explainer.routes.js";
import validationRoutes from "./modules/validation/validation.routes.js";
import refactorReviewRoutes from "./modules/refactor-review/refactor-review.routes.js";
import githubRoutes from "./modules/github/github.routes.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/workspaces", verifyToken, workspaceRoutes);
router.use("/parser", verifyToken, parserRoutes);
router.use("/chunks", verifyToken, chunkRoutes);
router.use("/graph", verifyToken, graphRoutes);
router.use("/file", verifyToken, fileRoutes);
router.use("/indexer", verifyToken, indexerRoutes);
router.use("/resolver", verifyToken, resolverRoutes);
router.use("/architecture", verifyToken, architectureRoutes);
router.use("/explainer", verifyToken, explainerRoutes);
router.use("/decision", verifyToken, decisionRoutes);
router.use("/context", verifyToken, contextRoutes);
router.use("/intent", verifyToken, intentRoutes);
router.use("/intelligence", verifyToken, intelligenceRoutes);
router.use("/planner", verifyToken, plannerRoutes);
router.use("/refactor", verifyToken, refactorRoutes);
router.use("/transformation", verifyToken, transformationRoutes);
router.use("/callgraph", verifyToken, callgraphRoutes);
router.use("/refactor-plan", verifyToken, refactorPlanRoutes);
router.use("/changeset", verifyToken, changesetRoutes);
router.use("/ast-refactor", verifyToken, astRefactorRoutes);
router.use("/changeset-executor", verifyToken, changeSetExecutorRoutes);
router.use("/diff-preview", verifyToken, diffPreviewRoutes);
router.use("/snapshot", verifyToken, snapshotRoutes);
router.use("/embedding", verifyToken, embeddingRoutes);
router.use("/ai", verifyToken, aiRoutes);
router.use("/repository", verifyToken, repositoryRoutes);
router.use("/flow-explain", verifyToken, flowExplainRoutes);
router.use("/validation", verifyToken, validationRoutes);
router.use("/refactor-review", verifyToken, refactorReviewRoutes);
router.use("/github", githubRoutes);

export default router;
